version: "3.9"

services:
  payment-service:
    build: .
    container_name: accesorios-payment-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=accesorios_db
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_SCHEMA=pago
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"